name: CI
on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20.3.1@sha256:57391181388cd89ede79f371e09373824051eb0f708165dcd0965f18b3682f35
      # this is the user that CI uses, which is needed to generate files within the repo directory
      options: --user 1001

    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup node cache
        uses: actions/setup-node@v5
        with:
          node-version: 22.20.0
          cache: 'pnpm'
      - name: Setup NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm run test -- --ci --maxWorkers=1 --reporters=default
